### ISSUE TITLE
Storage exceeding quota

### ISSUE THREAD

**Issue by ZachNagengast** [jenil/huntsplash#2]
Noticed the background image wasnt changing and saw in the console the following error:

```
Uncaught DOMException: Failed to set the 'bgData' property on 'Storage': Setting the value of 'bgData' exceeded the quota.
    at HTMLImageElement.r.onload 
```

The error appears to be thrown after the "BG cached" line.

**Comment by jenil** [comment]
Even I did get this error a couple of times, I ran `localStorage.clear()` once and it worked fine then. Did you manage to debug it?
